async_mode: threaded
cache:
  base_dir: cache
  type: file
chunks:
  group_by_columns:
  - id
  overlap: 0
  size: 1000
claim_extraction:
  description: Any claims or facts that could be relevant to information discovery.
  max_gleanings: 1
  prompt: prompts/claim_extraction.txt
cluster_graph:
  max_cluster_size: 10
community_reports:
  max_input_length: 8000
  max_length: 2000
  prompt: prompts/community_report.txt
embed_graph:
  enabled: false
embeddings:
  async_mode: threaded
  llm:
    api_base: ${GRAPHRAG_EMBEDDING_API_BASE}
    api_key: ${GRAPHRAG_EMBEDDING_API_KEY}
    api_version: ${GRAPHRAG_EMBEDDING_API_VERSION}
    deployment_name: ${GRAPHRAG_EMBEDDING_DEPLOYMENT_NAME}
    model: ${GRAPHRAG_EMBEDDING_MODEL}
    type: azure_openai_embedding
encoding_model: cl100k_base
entity_extraction:
  entity_types:
  - organization
  - person
  - geo
  - event
  max_gleanings: 1
  prompt: prompts/entity_extraction.txt
global_search: null
input:
  base_dir: ${GRAPHRAG_INPUT_BASE_DIR}
  file_encoding: utf-8
  file_pattern: .*\.txt$
  file_type: text
  type: file
llm:
  api_base: ${GRAPHRAG_API_BASE}
  api_key: ${GRAPHRAG_API_KEY}
  api_version: ${GRAPHRAG_API_VERSION}
  deployment_name: ${GRAPHRAG_LLM_DEPLOYMENT_NAME}
  max_tokens: 1024
  model: ${GRAPHRAG_LLM_MODEL}
  model_supports_json: true
  temperature: 0.5
  type: azure_openai_chat
local_search: null
parallelization:
  stagger: 0.3
reporting:
  base_dir: output/${timestamp}/reports
  type: file
skip_workflows: []
snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false
storage:
  base_dir: output/${timestamp}/artifacts
  type: file
  connection_string: ${GRAPHRAG_STORAGE_CONNECTION_STRING}
  container_name: ${GRAPHRAG_STORAGE_CONTAINER_NAME}
summarize_descriptions:
  max_length: 500
  prompt: prompts/summarize_descriptions.txt
umap:
  enabled: false
